@echo off
echo Installing dependencies...
call npm install
echo Generating Prisma client...
call npx prisma generate
echo Pushing schema to database...
call npx prisma db push
echo Seeding database...
call npx prisma db seed
echo Done.
